# Generated by Django 5.0.1 on 2024-01-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='feature/')),
                ('status', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=400)),
            ],
        ),
    ]
